name: Playwright Smoke Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  playwright:
    name: 'Playwright Tests - Smoke Check'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.42.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install playwright
          python -m pip install pytest-playwright
          python -m playwright install
          python -m pip install pytest-check
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run the smoke-checks
        run: |
          pytest test_in_sync.py -v
        env:
          HOME: /root


  API_checks:
      needs: playwright
      name: 'API - Smoke Check'
      runs-on: ubuntu-latest
      container:
        image: mcr.microsoft.com/playwright/python:v1.42.0-jammy
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install playwright
            python -m pip install pytest-playwright
            python -m playwright install
            python -m pip install pytest-check
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Run the smoke-checks
          run: |
            pytest test_apis.py -v
          env:
            HOME: /root
          
